SELECT CUST_DATA_RECORDS.REC_ID_NBR, CUST_DATA_RECORDS.ACTV_ID, CUST_DATA_RECORDS.EMAIL_ID,
CUST_DATA_RECORDS.REC_TMSP_TIME, CUST_DATA_RECORDS.LAST_UPDT_TIME, CUST_DATA_RECORDS.IS_CONFIRMED,
DATA.REC_ID_NBR, DATA.FIELD_NAME, DATA.COL_DATA_VALU_TEXT, COLUMN_ASSOCIATIONS.ASSC_COL_NAME
FROM CUST_DATA_RECORDS 
INNER JOIN DATA ON CUST_DATA_RECORDS.REC_ID_NBR=DATA.REC_ID_NBR
INNER JOIN COLUMN_ASSOCIATIONS ON COLUMN_ASSOCIATIONS.ACTV_ID=CUST_DATA_RECORDS.ACTV_ID 
WHERE (((CUST_DATA_RECORDS.ACTV_ID)=246) AND (DATA.FIELD_NAME = COLUMN_ASSOCIATIONS.FIELD_NAME));
