SELECT CUST_DATA_RECORDS.REC_ID_NBR, CUST_DATA_RECORDS.ACTV_ID, CUST_DATA_RECORDS.EMAIL_ID,
CUST_DATA_RECORDS.REC_TMSP_TIME, CUST_DATA_RECORDS.LAST_UPDT_TIME, CUST_DATA_RECORDS.IS_CONFIRMED,
USERINFO.REC_ID_NBR, USERINFO.FIELD_NAME, USERINFO.COL_DATA_VALU_TEXT
FROM CUST_DATA_RECORDS 
INNER JOIN USERINFO ON CUST_DATA_RECORDS.REC_ID_NBR = USERINFO.REC_ID_NBR
WHERE (((CUST_DATA_RECORDS.ACTV_ID)=246));
